# Generated by Django 4.2 on 2023-05-10 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gaminghub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='nombre_completo',
        ),
    ]
