# Generated by Django 4.2 on 2023-06-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gaminghub', '0002_mensaje_multimedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajegrupo',
            name='multimedia',
            field=models.FileField(null=True, upload_to='multimedia/'),
        ),
    ]
