# Generated by Django 4.2 on 2023-06-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gaminghub', '0002_mensaje_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='contenido',
            field=models.TextField(null=True),
        ),
    ]
