# Generated by Django 4.2 on 2023-06-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gaminghub', '0003_mensajegrupo_multimedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='descripcion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='genero',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
