# Generated by Django 4.2 on 2023-06-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gaminghub', '0003_alter_mensaje_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='multimedia',
            field=models.FileField(upload_to='multimedia/'),
        ),
    ]
