# Generated by Django 4.0.4 on 2023-05-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gaminghub', '0004_alter_publicacion_multimedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='multimedia',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
