# Generated by Django 4.2 on 2023-05-19 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gaminghub', '0005_alter_publicacion_multimedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('privacidad', models.IntegerField()),
                ('fk_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id_sala', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_sala', models.CharField(max_length=200)),
                ('fk_id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gaminghub.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id_miembro', models.BigAutoField(primary_key=True, serialize=False)),
                ('fk_id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gaminghub.grupo')),
                ('fk_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('fk_id_publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gaminghub.publicacion')),
                ('fk_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
