# Generated by Django 4.0.4 on 2023-05-20 22:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gaminghub', '0006_grupo_sala_miembro_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='dislike',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='like',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
