# Generated by Django 4.2 on 2023-05-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gaminghub', '0007_grupo_multimedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='multimedia',
            field=models.ImageField(default='static/img/Logo.png', max_length=200, upload_to=''),
        ),
    ]
