# Generated by Django 4.2 on 2023-05-24 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gaminghub', '0008_alter_grupo_multimedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amistad',
            fields=[
                ('id_amistad', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_amigo', models.IntegerField()),
                ('fk_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
