# Generated by Django 4.0.4 on 2023-05-24 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gaminghub', '0007_remove_publicacion_dislike_publicacion_dislike_and_more'),
        ('Gaminghub', '0009_amistad'),
    ]

    operations = [
    ]
