# Generated by Django 4.2 on 2023-05-24 03:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gaminghub', '0010_merge_20230523_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amistad',
            name='id_amigo',
        ),
        migrations.AddField(
            model_name='amistad',
            name='amigos',
            field=models.ManyToManyField(blank=True, related_name='amigos', to=settings.AUTH_USER_MODEL),
        ),
    ]
