# Generated by Django 4.2 on 2023-05-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gaminghub', '0011_remove_amistad_id_amigo_amistad_amigos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amistad',
            name='amigos',
        ),
        migrations.AddField(
            model_name='amistad',
            name='id_amigo',
            field=models.IntegerField(null=True),
        ),
    ]
