# Generated by Django 4.2 on 2023-05-24 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gaminghub', '0010_merge_20230523_2157'),
        ('Gaminghub', '0012_remove_amistad_amigos_amistad_id_amigo'),
    ]

    operations = [
    ]
