# Generated by Django 4.2 on 2023-05-26 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gaminghub', '0010_merge_20230524_1305'),
        ('Gaminghub', '0013_merge_20230524_1656'),
    ]

    operations = [
    ]
