# Generated by Django 4.2 on 2023-06-01 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gaminghub', '0015_alter_comentario_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amistad',
            name='fk_id_usuario',
        ),
        migrations.RemoveField(
            model_name='amistad',
            name='id_amigo',
        ),
        migrations.AddField(
            model_name='amistad',
            name='amigo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='amistad',
            name='persona',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.BigAutoField(primary_key=True, serialize=False)),
                ('recibidor', models.IntegerField(null=True)),
                ('fk_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('info', models.TextField(max_length=300, null=True)),
                ('recibidor', models.IntegerField(null=True)),
                ('fecha_creacion', models.DateField(null=True)),
                ('tipo', models.IntegerField(null=True)),
                ('fk_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
