# Generated by Django 4.2 on 2023-06-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gaminghub', '0016_remove_amistad_fk_id_usuario_remove_amistad_id_amigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
