# Generated by Django 4.0.4 on 2023-06-01 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gaminghub', '0014_merge_20230525_2053'),
        ('Gaminghub', '0017_alter_notificacion_fecha_creacion'),
    ]

    operations = [
    ]
