# Generated by Django 4.2 on 2023-06-01 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gaminghub', '0017_alter_notificacion_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='recibidor',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='fk_recibidor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='fk_id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_enviador', to=settings.AUTH_USER_MODEL),
        ),
    ]
