# Generated by Django 4.2 on 2023-06-01 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gaminghub', '0014_merge_20230525_2053'),
        ('Gaminghub', '0018_remove_notificacion_recibidor_and_more'),
    ]

    operations = [
    ]
