# Generated by Django 4.2 on 2023-06-08 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gaminghub', '0020_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='destinatario',
            field=models.ForeignKey(db_column='receptor_id', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_hora'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='remitente',
            field=models.ForeignKey(db_column='emisor_id', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL),
        ),
    ]
