# Generated by Django 4.2 on 2023-06-08 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gaminghub', '0022_alter_mensaje_destinatario_alter_mensaje_fecha_envio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='contenido',
            field=models.TextField(null=True),
        ),
    ]
