# Generated by Django 4.0.4 on 2023-06-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gaminghub', '0018_merge_20230601_1924'),
        ('Gaminghub', '0023_alter_mensaje_contenido'),
    ]

    operations = [
    ]
