# Generated by Django 4.2 on 2023-06-08 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gaminghub', '0023_alter_mensaje_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id_titulo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_titulo', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puntaje',
            fields=[
                ('id_puntaje', models.BigAutoField(primary_key=True, serialize=False)),
                ('puntos', models.IntegerField(null=True)),
                ('fk_id_titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gaminghub.titulo')),
                ('fk_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
