# Generated by Django 4.2 on 2023-06-08 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gaminghub', '0024_titulo_puntaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroGrupo',
            fields=[
                ('id_registro', models.BigAutoField(primary_key=True, serialize=False)),
                ('fk_id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gaminghub.grupo')),
                ('fk_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
