# Generated by Django 4.2 on 2023-06-09 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gaminghub', '0025_registrogrupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='contenido',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.CreateModel(
            name='MensajeGrupo',
            fields=[
                ('id_mensajeGrupo', models.BigAutoField(primary_key=True, serialize=False)),
                ('contenido', models.CharField(max_length=400, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fk_id_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gaminghub.sala')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
